# Generated by Django 5.1.1 on 2024-10-09 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0005_alter_spotifytoken_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifytoken',
            name='refresh_token',
        ),
    ]
