# Generated by Django 5.1.1 on 2024-10-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_remove_spotifytoken_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifytoken',
            name='access_token',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spotifytoken',
            name='token_type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spotifytoken',
            name='user',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
